feat: fetch usernames for waiting page
CS3219-AY2223S1/cs3219-project-ay2223s1-g5 pull request #91
Opened 2022-09-12 08:43 UTC by ypinhsuan

Closes #88

2022-09-12 10:15 UTC, dextertanyj requested changes
Some comments about how we can use `react-query`.

2022-09-12 10:15 UTC, dextertanyj commented on frontend/src/hooks/useUsers.ts
> +};
Let's use `react-query` to help us cache this:
```suggestion
export const useGetUserName = (userId?: number) => {
  const getUserName = async () => {
    const { data } = await ApiService.get<GetUserNameRes | undefined>(
      `/users/${userId}`,
    );
    return data;
  };
  const { data: user, isLoading: isGetUserNameLoading } = useQuery(
    ["USER", userId?.toString() || ""],
    getUserName,
    {
      enabled: !!userId,
    },
  );
  return {
    user,
    isGetUserNameLoading,
  };
};
```

2022-09-12 10:15 UTC, dextertanyj commented on frontend/src/pages/WaitingPage.tsx
> +  const { getUsername } = useGetUsername();
If we use `react-query`, then we will need to `useState` to fire off the queries when the user IDs become available.

```suggestion
  const [userOne, setUserOne] = useState<number | undefined>(undefined);
  const [userTwo, setUserTwo] = useState<number | undefined>(undefined);
  const [roomId, setRoomId] = useState<string | undefined>(undefined);
  const { user: userNameOne } = useGetUserName(userOne);
  const { user: userNameTwo } = useGetUserName(userTwo);
```

2022-09-12 10:15 UTC, dextertanyj commented on frontend/src/pages/WaitingPage.tsx
> +    socket.on("found", async (match: Match) => {
Then we can use this to set the states when we receive the event:
```
      setUserOne(match.result[0].userId);
      setUserTwo(match.result[1].userId);
      setRoomId(match.roomId);
      setMessage("Match found. Loading information...");
      clearTimeout(timeout);
```

2022-09-12 10:15 UTC, dextertanyj commented on frontend/src/pages/WaitingPage.tsx
> +
And we can use a `useEffect` hook to set the message when all the data is available.
```
  useEffect(() => {
    if (roomId && userNameOne && userNameTwo) {
      setMessage(
        `Found a match between ${userNameOne.name} and ${userNameTwo.name}!
        Room ID: ${roomId}
        Loading...`,
      );
    }
  }, [roomId, userNameOne, userNameTwo]);
```

2022-09-13 00:53 UTC, ypinhsuan commented
Thanks for the guide! I was quite confused about how to use react hook inside a callback 😅

2022-09-13 01:36 UTC, dextertanyj approved these changes
lgtm

2022-09-13 04:45 UTC, merged